export function queryElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) {
    throw new Error(`Missing required element: ${selector}`);
  }

  return element;
}

export const elements = {
  html: document.documentElement,
  canvasStage: queryElement<HTMLElement>("#canvas-stage"),
  canvasSvg: queryElement<SVGSVGElement>("#canvas-svg"),
  worldLayer: queryElement<SVGGElement>("#world-layer"),
  overlayLayer: queryElement<SVGGElement>("#overlay-layer"),
  inlineEditor: queryElement<HTMLTextAreaElement>("#inline-editor"),
  boardTitleInput: queryElement<HTMLInputElement>("#board-title-input"),
  persistenceStatus: queryElement<HTMLElement>("#persistence-status"),
  shareBoardButton: queryElement<HTMLButtonElement>("#share-board-btn"),
  newBoardButton: queryElement<HTMLButtonElement>("#new-board-btn"),
  libraryButton: queryElement<HTMLButtonElement>("#library-btn"),
  undoButton: queryElement<HTMLButtonElement>("#undo-btn"),
  redoButton: queryElement<HTMLButtonElement>("#redo-btn"),
  themeButton: queryElement<HTMLButtonElement>("#theme-btn"),
  themeIcon: queryElement<SVGUseElement>("#theme-icon"),
  zoomOutButton: queryElement<HTMLButtonElement>("#zoom-out-btn"),
  zoomInButton: queryElement<HTMLButtonElement>("#zoom-in-btn"),
  zoomFitButton: queryElement<HTMLButtonElement>("#zoom-fit-btn"),
  gridToggleButton: queryElement<HTMLButtonElement>("#grid-toggle-btn"),
  shapeSelector: queryElement<HTMLDetailsElement>("[data-shape-menu]"),
  shapeMenuOptions: queryElement<HTMLElement>("[data-shape-options]"),
  shapeSelectorTrigger: queryElement<HTMLElement>("[data-shape-trigger]"),
  currentShapeIcon: queryElement<SVGUseElement>("[data-current-shape-icon]"),
  inspector: queryElement<HTMLElement>("#inspector"),
  selectionChip: queryElement<HTMLElement>(".selection-chip"),
  editTextButton: queryElement<HTMLButtonElement>("#edit-text-btn"),
  primaryContextSeparator: queryElement<HTMLElement>(".primary-context-separator"),
  fillControl: queryElement<HTMLElement>(".fill-control"),
  fillControlTrigger: queryElement<HTMLElement>(".fill-control > summary"),
  strokeControl: queryElement<HTMLElement>(".stroke-control"),
  textStyleControl: queryElement<HTMLElement>(".text-style-control"),
  routeArrowButton: queryElement<HTMLButtonElement>("#route-arrow-btn"),
  arrowHeadControl: queryElement<HTMLElement>(".arrow-head-control"),
  currentArrowHead: queryElement<SVGUseElement>("[data-current-arrow-head]"),
  currentFillSwatch: queryElement<HTMLElement>("[data-current-fill]"),
  currentStrokeSwatch: queryElement<HTMLElement>("[data-current-stroke]"),
  currentLineStyle: queryElement<HTMLElement>("[data-current-line-style]"),
  currentFontSize: queryElement<HTMLElement>("[data-current-font-size]"),
  textValueInput: queryElement<HTMLTextAreaElement>("#text-value-input"),
  fillColorInput: queryElement<HTMLInputElement>("#fill-color-input"),
  strokeColorInput: queryElement<HTMLInputElement>("#stroke-color-input"),
  lineStyleControl: queryElement<HTMLElement>(".line-style-control"),
  textColorInput: queryElement<HTMLInputElement>("#text-color-input"),
  fontSizeInput: queryElement<HTMLInputElement>("#font-size-input"),
  boldTextButton: queryElement<HTMLButtonElement>("#bold-text-btn"),
  italicTextButton: queryElement<HTMLButtonElement>("#italic-text-btn"),
  lockSelectionButton: queryElement<HTMLButtonElement>("#lock-selection-btn"),
  lockSelectionIcon: queryElement<SVGUseElement>("#lock-selection-icon"),
  arrangeControl: queryElement<HTMLElement>(".arrange-control"),
  bringFrontButton: queryElement<HTMLButtonElement>("#bring-front-btn"),
  sendBackButton: queryElement<HTMLButtonElement>("#send-back-btn"),
  arrangeContextSeparator: queryElement<HTMLElement>(".arrange-context-separator"),
  duplicateButton: queryElement<HTMLButtonElement>("#duplicate-btn"),
  deleteSelectionButton: queryElement<HTMLButtonElement>("#delete-selection-btn"),
  importButton: queryElement<HTMLButtonElement>("#import-btn"),
  importFileInput: queryElement<HTMLInputElement>("#import-file-input"),
  exportJsonButton: queryElement<HTMLButtonElement>("#export-json-btn"),
  exportImageButton: queryElement<HTMLButtonElement>("#export-image-btn"),
  exportMenu: queryElement<HTMLElement>("#export-menu"),
  exportMenuSvgButton: queryElement<HTMLButtonElement>("#export-menu-svg-btn"),
  exportMenuPngButton: queryElement<HTMLButtonElement>("#export-menu-png-btn"),
  libraryDialog: queryElement<HTMLDialogElement>("#library-dialog"),
  boardList: queryElement<HTMLElement>("#board-list"),
  commandDialog: queryElement<HTMLDialogElement>("#command-dialog"),
  commandInput: queryElement<HTMLInputElement>("#command-input"),
  commandList: queryElement<HTMLElement>("#command-list"),
  toast: queryElement<HTMLElement>("#toast"),
};
